#ifndef NETWORK_CONSTANTS
#define NETWORK_CONSTANTS


#define MAX_SEARCH_TIME 10
#define MAX_LISTEN_TIME 10

enum REQUEST_STATUS {
  SEARCH_CONNECTION,
  SUCCESS_CONNECTION
};

enum RESPONSE_STATUS
{
    NONE_RESPONSE,
    CONNECTION_AVAILABLE,
    ESTABLISHED_CONNECTION
};


namespace PORTS {
    const unsigned short SEND_SERVER_RECEPTION_CLIENT = 7008;
    const unsigned short SEND_CLIENT_RECEPTION_SERVER = 8007;
}

#endif